# Generated by Django 4.0.6 on 2022-07-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_character_year_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='year_created',
            field=models.IntegerField(),
        ),
    ]
