# Generated by Django 4.0.6 on 2022-07-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_character_year_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='movie_format',
            field=models.BooleanField(),
        ),
    ]
