# Generated by Django 4.0.6 on 2022-07-26 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_character_movie_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('G', 'Good'), ('B', 'Bad'), ('N', 'Necessary/Neutral'), ('S', 'Subjective')], default='N', max_length=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.character')),
            ],
        ),
    ]
